### ISSUE TITLE
Include instructions for building project with Docker

### ISSUE THREAD

**Issue by tallamjr** [alan-turing-institute/simurgh#1]
It would be desirable to have a complete packaged install available using docker.

A nice to have would be for `bluesky`, `bluebird`, `dodo` and `twitcher` to be launched with a single `docker-compose.yml` file (not sure if this is even possible)

**Comment by rkm** [comment]
This should definitely be possible! I created a [docker-compose](https://github.com/alan-turing-institute/twitcher/pull/8/files) which includes BlueSky, BlueBird, and Twitcher - adding in Dodo should be straightforward.
