### ISSUE TITLE
Fix docker setup and update versions

### ISSUE THREAD

**Issue by evelinag** [alan-turing-institute/simurgh#15]
I wanted to test the latest setup with the new Twitcher but I'm having problems making it work together. I'm using the `docker-compose.yml` file and updating bluebird to either `image: turinginst/bluebird:2.0.0` or `image: turinginst/bluebird:latest`. In both versions, bluebird fails to see Bluesky image running and fails.

**Comment by rkm** [comment]
I think this is because the minimum version of BlueSky required is now `1.4.1`, so this needs to be updated in the docker-compose file. I tried to update this myself but don't have write access to this repo.

**Comment by radka-j** [comment]
yes sorry about this! as pointed out, the issue is the bluesky version. fixing this now.
