### ISSUE TITLE
scenario generation

### ISSUE THREAD

**Issue by arunbalas** [alan-turing-institute/simurgh#22]
I would like to know if there are csv files that were used to generate sample scenarios using aviary?

**Comment by evelinag** [comment]
We're working on creating some demo files for aviary - pinging @thobson88 

Unfortunately our current aircraft performance data files are licensed and we cannot publish them.

**Comment by thobson88** [comment]
Sorry- I hadn't seen this ticket. It's a duplicate of [aviary issue 42](https://github.com/alan-turing-institute/aviary/issues/42) which has been addressed.
